### ISSUE TITLE
Unknown method name `parameterInputFeature'

### ISSUE THREAD

**Issue by SamyRai** [chinshr/diarize-ruby#9]
Hi Juergen, I am trying to use your gem to diarize audio, but getting this error when trying to analyze it:
`*** RuntimeError Exception: Fail: unknown method name `parameterInputFeature'`
Do you know how to fix it? 
I use: 2.4.1 ruby, openjdk 1.8

**Comment by chinshr** [comment]
I have not tested with the ruby version you are using. Could you try with ~v2.2 and 2.3?

**Comment by chinshr** [comment]
@SamyRai could you please also post a full stack trace?

**Comment by SamyRai** [comment]
@chinshr Sorry for delay with answer, for that time I just switched to version 2.3 and it worked.

**Comment by Ammet** [comment]
Same for me. Not working both on 2.2.* and 2.3.*
```
2.3.1 :003 > audio.analyze!
RuntimeError: Fail: unknown method name `parameterInputFeature'
	from /Users/ilya/work/air/diarize-ruby/lib/diarize/audio.rb:44:in `method_missing'
	from /Users/ilya/work/air/diarize-ruby/lib/diarize/audio.rb:44:in `analyze!'
	from (irb):3
	from /Users/ilya/work/air/diarize-ruby/bin/diarize:50:in `block (2 levels) in <top (required)>'
	from /Users/ilya/.rvm/gems/ruby-2.3.1/gems/gli-2.18.2/lib/gli/command_support.rb:131:in `execute'
	from /Users/ilya/.rvm/gems/ruby-2.3.1/gems/gli-2.18.2/lib/gli/app_support.rb:296:in `block in call_command'
	from /Users/ilya/.rvm/gems/ruby-2.3.1/gems/gli-2.18.2/lib/gli/app_support.rb:309:in `call_command'
	from /Users/ilya/.rvm/gems/ruby-2.3.1/gems/gli-2.18.2/lib/gli/app_support.rb:83:in `run'
	from /Users/ilya/work/air/diarize-ruby/bin/diarize:176:in `<top (required)>'
	from /Users/ilya/.rvm/gems/ruby-2.3.1/bin/diarize:22:in `load'
	from /Users/ilya/.rvm/gems/ruby-2.3.1/bin/diarize:22:in `<main>'
	from /Users/ilya/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ilya/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```
